---
title: "R Notebook"
output: html_notebook
---



```{r}
library(tidyverse)
library(geojsonio)
library(broom)
library(sf)
library(osmdata)
library(ggplot2)
library(dplyr)
library(ggnewscale)
library(leaflet.extras)
```


```{r}
#### Load the Restaurant dataset
data = read.csv("DOHMH_New_York_City_Restaurant_Inspection_Results.csv")
data$year <- format(as.Date(data$INSPECTION.DATE, format="%d/%m/%Y"),"%Y") ## Extract Years

###filter the dataset
df =
  data %>%
  filter(data$year >= 2019 & ZIPCODE!="" & DBA != "") %>%
  mutate(GRADE=replace(GRADE, GRADE == "", NA))

head(df)
```


```{r}
# Read the geojson file containing Spatial Info
spdf_file <- geojson_read(   "zip_code_040114.geojson", what = "sp")

stats_df = spdf_file@data

# Convert it to a spatial data frame, with zip code as index
spdf_data <- tidy(  spdf_file,
  region="ZIPCODE"  # Use ZIPCODE variable as index, the index will be named "id"
)
```

```{r}

### Grade info for each type of restaurant
grades =
  df %>% 
  group_by(DBA, Latitude, Longitude) %>%   ##windows function partition by DBA, Lat, and Long
  mutate(rowNum = row_number(desc(INSPECTION.DATE))) %>% #specify how to list row numbers here; desc for latest first.
  filter(rowNum == 1)%>%
  drop_na(Longitude)%>% 
  mutate(CUISINE.TYPE = 
           case_when(CUISINE.DESCRIPTION == "American" ~ "American", 
                     CUISINE.DESCRIPTION == "Chinese" ~ "Chinese",
                     CUISINE.DESCRIPTION == "Coffee/Tea" ~ "Coffee", 
                     CUISINE.DESCRIPTION == "Pizza" ~ "Pizza",
                     CUISINE.DESCRIPTION == "Italian" ~ "Italian", 
                     CUISINE.DESCRIPTION == "Mexican" ~ "Mexican",
                     TRUE ~ "Others"))

American = 
  grades%>%filter(CUISINE.TYPE == "American")

Chinese= 
  grades%>%filter(CUISINE.TYPE == "Chinese")

Coffee = 
  grades%>%filter(CUISINE.TYPE == "Coffee")

Italian = 
  grades%>%filter(CUISINE.TYPE == "Italian")

Pizza = 
  grades%>%filter(CUISINE.TYPE == "Pizza")

Mexican = 
  grades%>%filter(CUISINE.TYPE == "Mexican")

Others = 
  grades%>%filter(CUISINE.TYPE == "Others")

```





```{r}

##### None Interactive map (Population by region)
ggplot() +
  geom_polygon(data=spdf_data %>%
                 left_join(stats_df, c("id"="ZIPCODE")),
               aes(x=long,
                   y=lat,
                   group=group,
                   fill=POPULATION),
               color="white",
               size=.2) +
  theme_void() +
  coord_map() +
  scale_fill_distiller(palette = "YlGnBu", direction = 1) +
  labs(title="Population in New York City",
       subtitle="Neighborhoods are filled by population",
       fill="Population")
```





```{r}

#### Number of restaurant per ZIPCODE
Num_Rest_Code =
  df%>%
  group_by(ZIPCODE, DBA, Latitude, Longitude)%>%
  count() %>%
  group_by(ZIPCODE)%>%
  count()

Critical_2019_by_Code = 
  df%>%
  filter(year == 2019)%>%
  group_by(ZIPCODE)%>%
  summarize(Total = n())
  
Critical_2020_by_Code = 
  df%>%
  filter(year == 2020)%>%
  group_by(ZIPCODE)%>%
  summarize(Total = n())
  
Critical_2021_by_Code = 
  df%>%
  filter(year == 2021)%>%
  group_by(ZIPCODE)%>%
  summarize(Total = n())
  
Critical_2022_by_Code = 
  df%>%
  filter(year == 2022)%>%
  group_by(ZIPCODE)%>%
  summarize(Total = n())


spdf_file_2022 = spdf_file
spdf_file_2022@data =
spdf_file_2022@data %>%
                 left_join(Critical_2022_by_Code, c("ZIPCODE"="ZIPCODE"))



spdf_file_2019 = spdf_file
spdf_file_2019@data =
spdf_file_2019@data %>%
                 left_join(Critical_2019_by_Code, c("ZIPCODE"="ZIPCODE"))


spdf_file_2020 = spdf_file
spdf_file_2020@data =
spdf_file_2020@data %>%
                 left_join(Critical_2020_by_Code, c("ZIPCODE"="ZIPCODE"))

spdf_file_2021 = spdf_file
spdf_file_2021@data =
spdf_file_2021@data %>%
                 left_join(Critical_2021_by_Code, c("ZIPCODE"="ZIPCODE"))







nc_pal= colorNumeric(palette="YlOrBr", domain= spdf_file_2019@data$Total, na.color = 'transparent')


Critical_Violation_Map=
leaflet()%>%
  addProviderTiles("CartoDB")%>%
  addSearchOSM()%>%
  addReverseSearchOSM()%>%
  #### First Layer of PolyGons
  addPolygons(
    data = spdf_file_2022 ,
    weight = 0.5,
    color = "black",
    stroke=TRUE ,
    opacity = 1 ,
    fillColor = ~nc_pal(Total),
    label = ~paste0 ('Total Critical Violation : ' , Total),
    group = '2022',
    fillOpacity = 0.7,
    highlight = highlightOptions(weight  = 3, color = "red", bringToFront =  T)
    ) %>%
  
  #### Second Layer of PolyGons
    addPolygons(
    data = spdf_file_2021 ,
    weight = 0.5,
    color = "black",
    stroke=TRUE ,
    opacity = 1 ,
    fillColor = ~nc_pal(Total),
    label =~paste0 ('Total Critical Violation : ' , Total),
    group = '2021',
    fillOpacity = 0.7,
    highlight = highlightOptions(weight  = 3, color = "red", bringToFront =  T)
    ) %>%
  
  addPolygons(
    data = spdf_file_2020 ,
    weight = 0.5,
    color = "black",
    stroke=TRUE ,
    opacity = 1 ,
    fillColor = ~nc_pal(Total),
    label = ~paste0 ('Total Critical Violation : ' , Total),
    group = '2020',
    fillOpacity = 0.7,
    highlight = highlightOptions(weight  = 3, color = "red", bringToFront =  T)
    ) %>%
  
  #### Third Layer of PolyGons
    addPolygons(
    data = spdf_file_2019 ,
    weight = 0.5,
    color = "black",
    stroke=TRUE ,
    opacity = 1 ,
    fillColor = ~nc_pal(Total),
    label =~paste0 ('Total Critical Violation : ' , Total),
    group = '2019',
    fillOpacity = 0.7,
    highlight = highlightOptions(weight  = 3, color = "red", bringToFront =  T)
    ) %>%
  
   ##### layer of grades of restaurnts
  
  addMarkers(data = American,lng = ~Longitude, lat = ~Latitude, 
                  
                   label = ~htmlEscape(DBA),
                   group = 'American',
                   popup  = paste0("<b>",American$DBA,"</b>", 
                                   "<br/>", 'Cuisine Type: ', American$CUISINE.DESCRIPTION, 
                                   "<br/>", 'Phone Number: ', American$PHONE,
                                   "<br/>", 'Grade: ', American$GRADE,
                                  "<br/>",'Latest Violation: ', American$VIOLATION.DESCRIPTION ),
                  clusterOptions = markerClusterOptions()
             ) %>% 
   addMarkers(data = Chinese,lng = ~Longitude, lat = ~Latitude, 
                   label = ~htmlEscape(DBA),
                   group = 'Chinese',
                   popup  = paste0("<b>",Chinese$DBA,"</b>", 
                                   "<br/>", 'Cuisine Type: ', Chinese$CUISINE.DESCRIPTION, 
                                   "<br/>", 'Phone Number: ', Chinese$PHONE,
                                   "<br/>", 'Grade: ', Chinese$GRADE,
                                  "<br/>",'Latest Violation: ', Chinese$VIOLATION.DESCRIPTION ),
                  clusterOptions = markerClusterOptions()
             ) %>% 
  
   addMarkers(data = Pizza,lng = ~Longitude, lat = ~Latitude, 
              
                   label = ~htmlEscape(DBA),
                   group = 'Pizza',
                   popup  = paste0("<b>",Pizza$DBA,"</b>", 
                                   "<br/>", 'Cuisine Type: ', Pizza$CUISINE.DESCRIPTION, 
                                   "<br/>", 'Phone Number: ', Pizza$PHONE,
                                   "<br/>", 'Grade: ', Pizza$GRADE,
                                  "<br/>",'Latest Violation: ', Pizza$VIOLATION.DESCRIPTION ),
                  clusterOptions = markerClusterOptions()
             ) %>% 
  
   
   addMarkers(data = Mexican,lng = ~Longitude, lat = ~Latitude, 
                   label = ~htmlEscape(DBA),
                   group = 'Mexican',
                   popup  = paste0("<b>",Mexican$DBA,"</b>", 
                                   "<br/>", 'Cuisine Type: ', Mexican$CUISINE.DESCRIPTION, 
                                   "<br/>", 'Phone Number: ', Mexican$PHONE,
                                   "<br/>", 'Grade: ', Mexican$GRADE,
                                  "<br/>",'Latest Violation: ', Mexican$VIOLATION.DESCRIPTION ),
                  clusterOptions = markerClusterOptions()
             ) %>% 
  
  
   addMarkers(data = Italian,lng = ~Longitude, lat = ~Latitude, 
                   label = ~htmlEscape(DBA),
                   group = 'Italian',
                   popup  = paste0("<b>",Italian$DBA,"</b>", 
                                   "<br/>", 'Cuisine Type: ', Italian$CUISINE.DESCRIPTION, 
                                   "<br/>", 'Phone Number: ', Italian$PHONE,
                                   "<br/>", 'Grade: ', Italian$GRADE,
                                  "<br/>",'Latest Violation: ', Italian$VIOLATION.DESCRIPTION ),
                  clusterOptions = markerClusterOptions()
             ) %>% 
  addMarkers(data = Coffee,lng = ~Longitude, lat = ~Latitude, 
                   label = ~htmlEscape(DBA),
                   group = 'Coffee',
                   popup  = paste0("<b>",Coffee$DBA,"</b>", 
                                   "<br/>", 'Cuisine Type: ', Coffee$CUISINE.DESCRIPTION, 
                                   "<br/>", 'Phone Number: ', Coffee$PHONE,
                                   "<br/>", 'Grade: ', Coffee$GRADE,
                                  "<br/>",'Latest Violation: ', Coffee$VIOLATION.DESCRIPTION ),
                  clusterOptions = markerClusterOptions()
             ) %>% 
  addMarkers(data = Others,lng = ~Longitude, lat = ~Latitude, 
                   label = ~htmlEscape(DBA),
                   group = 'Others',
                   popup  = paste0("<b>",Others$DBA,"</b>", 
                                   "<br/>", 'Cuisine Type: ', Others$CUISINE.DESCRIPTION, 
                                   "<br/>", 'Phone Number: ', Others$PHONE,
                                   "<br/>", 'Grade: ', Others$GRADE,
                                  "<br/>",'Latest Violation: ', Others$VIOLATION.DESCRIPTION ),
                  clusterOptions = markerClusterOptions()
             ) %>% 
  
  
  addLayersControl( baseGroups = c("2022", "2021","2020","2019"),overlayGroups = c("American", "Chinese","Coffee","Pizza", "Italian","Mexican", "Others"))%>%
  addLegend( pal=nc_pal, values= spdf_file_2022$Total, opacity=0.9, title = "Critical Violation Counts", position = "bottomleft" )

Critical_Violation_Map
    
```






```{r}
Total_2019_by_Code = 
  df%>%
  filter(year == 2019 & CRITICAL.FLAG %in% c('Critical', 'Not Critical'))%>%
  group_by(ZIPCODE)%>%
  summarize(Total = n())
  
Total_2020_by_Code = 
  df%>%
  filter(year == 2020 & CRITICAL.FLAG %in% c('Critical', 'Not Critical'))%>%
  group_by(ZIPCODE)%>%
  summarize(Total = n())
  
Total_2021_by_Code = 
  df%>%
  filter(year == 2021 & CRITICAL.FLAG %in% c('Critical', 'Not Critical'))%>%
  group_by(ZIPCODE)%>%
  summarize(Total = n())
  
Total_2022_by_Code = 
  df%>%
  filter(year == 2022 & CRITICAL.FLAG %in% c('Critical', 'Not Critical'))%>%
  group_by(ZIPCODE)%>%
  summarize(Total = n())





##### Join datasets
spdf_file_2022 = spdf_file
spdf_file_2022@data =
spdf_file_2022@data %>%
                 left_join(Total_2022_by_Code, c("ZIPCODE"="ZIPCODE"))



spdf_file_2019 = spdf_file
spdf_file_2019@data =
spdf_file_2019@data %>%
                 left_join(Total_2019_by_Code, c("ZIPCODE"="ZIPCODE"))


spdf_file_2020 = spdf_file
spdf_file_2020@data =
spdf_file_2020@data %>%
                 left_join(Total_2020_by_Code, c("ZIPCODE"="ZIPCODE"))

spdf_file_2021 = spdf_file
spdf_file_2021@data =
spdf_file_2021@data %>%
                 left_join(Total_2021_by_Code, c("ZIPCODE"="ZIPCODE"))






##### colors
nc_pal= colorNumeric(palette="YlOrBr", domain= spdf_file_2019@data$Total, na.color = 'transparent')


Total_Violation_Map=
  
leaflet()%>%
  addProviderTiles("CartoDB")%>%
  setView(lng= -73.95223 , lat =40.78410	 , zoom = 10)%>%
  addSearchOSM()%>%
  addReverseSearchOSM()%>%
  #### First Layer of PolyGons
  addPolygons(
    data = spdf_file_2022 ,
    weight = 0.5,
    color = "black",
    stroke=TRUE ,
    opacity = 1 ,
    fillColor = ~nc_pal(Total),
    label = ~paste0 ('Total Critical Violation : ' , Total),
    group = '2022',
    fillOpacity = 0.7,   
    highlight = highlightOptions(weight  = 3, color = "red", bringToFront =  T)
    ) %>%
  
  #### Second Layer of PolyGons
    addPolygons(
    data = spdf_file_2021 ,
    weight = 0.5,
    color = "black",
    stroke=TRUE ,
    opacity = 1 ,
    fillColor = ~nc_pal(Total),
    label =~paste0 ('Total  Violation : ' , Total),
    group = '2021',
    fillOpacity = 0.7,
    highlight = highlightOptions(weight  = 3, color = "red", bringToFront =  T)
    ) %>%
    addLayersControl(overlayGroups = c("2022", "2021"))%>%
  
  #####Third layer
    addPolygons(
    data = spdf_file_2020 ,
    weight = 0.5,
    color = "black",
    stroke=TRUE ,
    opacity = 1 ,
    fillColor = ~nc_pal(Total),
    fillOpacity = 0.7,
    label =~paste0 ('Total  Violation : ' , Total),
    group = '2020',
    highlight = highlightOptions(weight  = 3, color = "red", bringToFront =  T)
    ) %>%
  
  ####Fourth Layer
    addPolygons(
    data = spdf_file_2019 ,
    weight = 0.5,
    color = "black",
    stroke=TRUE ,
    opacity = 1 ,
    fillColor = ~nc_pal(Total),
    label =~paste0 ('Total  Violation : ' , Total),
    group = '2019',
    fillOpacity = 0.7,
    highlight = highlightOptions(weight  = 3, color = "red", bringToFront =  T)
    ) %>%
   
  
  ##### Fifth layer of grades of restaurants
  

  
  addMarkers(data = American,lng = ~Longitude, lat = ~Latitude, 
                  
                   label = ~htmlEscape(DBA),
                   group = 'American',
                   popup  = paste0("<b>",American$DBA,"</b>", 
                                   "<br/>", 'Cuisine Type: ', American$CUISINE.DESCRIPTION, 
                                   "<br/>", 'Phone Number: ', American$PHONE,
                                   "<br/>", 'Grade: ', American$GRADE,
                                  "<br/>",'Latest Violation: ', American$VIOLATION.DESCRIPTION ),
                  clusterOptions = markerClusterOptions()
             ) %>% 
   addMarkers(data = Chinese,lng = ~Longitude, lat = ~Latitude, 
                   label = ~htmlEscape(DBA),
                   group = 'Chinese',
                   popup  = paste0("<b>",Chinese$DBA,"</b>", 
                                   "<br/>", 'Cuisine Type: ', Chinese$CUISINE.DESCRIPTION, 
                                   "<br/>", 'Phone Number: ', Chinese$PHONE,
                                   "<br/>", 'Grade: ', Chinese$GRADE,
                                  "<br/>",'Latest Violation: ', Chinese$VIOLATION.DESCRIPTION ),
                  clusterOptions = markerClusterOptions()
             ) %>% 
  
   addMarkers(data = Pizza,lng = ~Longitude, lat = ~Latitude, 
              
                   label = ~htmlEscape(DBA),
                   group = 'Pizza',
                   popup  = paste0("<b>",Pizza$DBA,"</b>", 
                                   "<br/>", 'Cuisine Type: ', Pizza$CUISINE.DESCRIPTION, 
                                   "<br/>", 'Phone Number: ', Pizza$PHONE,
                                   "<br/>", 'Grade: ', Pizza$GRADE,
                                  "<br/>",'Latest Violation: ', Pizza$VIOLATION.DESCRIPTION ),
                  clusterOptions = markerClusterOptions()
             ) %>% 
  
   
   addMarkers(data = Mexican,lng = ~Longitude, lat = ~Latitude, 
                   label = ~htmlEscape(DBA),
                   group = 'Mexican',
                   popup  = paste0("<b>",Mexican$DBA,"</b>", 
                                   "<br/>", 'Cuisine Type: ', Mexican$CUISINE.DESCRIPTION, 
                                   "<br/>", 'Phone Number: ', Mexican$PHONE,
                                   "<br/>", 'Grade: ', Mexican$GRADE,
                                  "<br/>",'Latest Violation: ', Mexican$VIOLATION.DESCRIPTION ),
                  clusterOptions = markerClusterOptions()
             ) %>% 
  
  
   addMarkers(data = Italian,lng = ~Longitude, lat = ~Latitude, 
                   label = ~htmlEscape(DBA),
                   group = 'Italian',
                   popup  = paste0("<b>",Italian$DBA,"</b>", 
                                   "<br/>", 'Cuisine Type: ', Italian$CUISINE.DESCRIPTION, 
                                   "<br/>", 'Phone Number: ', Italian$PHONE,
                                   "<br/>", 'Grade: ', Italian$GRADE,
                                  "<br/>",'Latest Violation: ', Italian$VIOLATION.DESCRIPTION ),
                  clusterOptions = markerClusterOptions()
             ) %>% 
  addMarkers(data = Coffee,lng = ~Longitude, lat = ~Latitude, 
                   label = ~htmlEscape(DBA),
                   group = 'Coffee',
                   popup  = paste0("<b>",Coffee$DBA,"</b>", 
                                   "<br/>", 'Cuisine Type: ', Coffee$CUISINE.DESCRIPTION, 
                                   "<br/>", 'Phone Number: ', Coffee$PHONE,
                                   "<br/>", 'Grade: ', Coffee$GRADE,
                                  "<br/>",'Latest Violation: ', Coffee$VIOLATION.DESCRIPTION ),
                  clusterOptions = markerClusterOptions()
             ) %>% 
  addMarkers(data = Others,lng = ~Longitude, lat = ~Latitude, 
                   label = ~htmlEscape(DBA),
                   group = 'Others',
                   popup  = paste0("<b>",Others$DBA,"</b>", 
                                   "<br/>", 'Cuisine Type: ', Others$CUISINE.DESCRIPTION, 
                                   "<br/>", 'Phone Number: ', Others$PHONE,
                                   "<br/>", 'Grade: ', Others$GRADE,
                                  "<br/>",'Latest Violation: ', Others$VIOLATION.DESCRIPTION ),
                  clusterOptions = markerClusterOptions()
             ) %>% 
  
  
  addLayersControl( baseGroups = c("2022", "2021","2020","2019"),overlayGroups = c("American", "Chinese","Coffee","Pizza", "Italian","Mexican", "Others"))%>%
  addLegend( pal=nc_pal, values= spdf_file_2022$Total, opacity=0.9, title = "Total Violation Counts", position = "bottomleft" )

Total_Violation_Map
```


